Dev
Nerubes/review2 pull request #1
Opened 2021-05-03 10:44 UTC by Nerubes

2021-05-12 08:55 UTC, corwinnn commented on parse.py
> +        string.find_all("span", class_="update-info"))[27:][:-8]
магические константы

2021-05-12 08:55 UTC, corwinnn commented on parse.py
> +    for href in hrefs:
enumerate?

2021-05-17 13:59 UTC, corwinnn requested changes

2021-05-17 13:59 UTC, corwinnn commented on const.py
> +TOKEN = "1881511655:AAEwLZaRF5rdv5f0azTU-FX5HToVa4vejmc"
убери

2021-05-17 13:59 UTC, corwinnn commented on main.py
> +        return user_id, const.NOTHING, "Invalid Command. Type /help for all commands.", 1
там же есть декораторы для команд

2021-05-17 13:59 UTC, corwinnn commented on main.py
> +    return res
join

2021-05-17 13:59 UTC, corwinnn commented on main.py
> +    if res == []:
if not res

2021-05-17 13:59 UTC, corwinnn commented on parse.py
> +    else:
else не нужно

2021-05-17 13:59 UTC, corwinnn commented on parse.py
> +        i = ("https://yummyanime.club/" + get_name(str(href), "src"), get_name(str(href), "alt"),
плохое название переменной

2021-05-17 13:59 UTC, corwinnn commented on parse.py
> +    while res == []:
not res

2021-05-17 13:59 UTC, corwinnn commented on parse.py
> +                i = ("https://yummyanime.club/" + get_name(str(href), "src"), get_update(href),
bad name

2021-05-17 13:59 UTC, corwinnn commented on parse.py
> +        i = "https://yummyanime.club/" + str(anims["image"]), str(
bad name

2021-05-19 00:12 UTC, Nerubes commented on main.py
> +        return user_id, const.NOTHING, "Invalid Command. Type /help for all commands.", 1
есть, но разносить немного больно уже

2021-05-19 11:56 UTC, corwinnn requested changes

2021-05-19 11:56 UTC, corwinnn commented on main.py
> +bot = tb.TeleBot(const.TOKEN)
там такого нет

2021-05-19 11:56 UTC, corwinnn commented on main.py
> +        bot.send_photo(res[0], res[1], res[2])
непонятны индексы

2021-05-19 11:56 UTC, corwinnn commented on main.py
> +        return user_id, const.NOTHING, "Invalid Command. Type /help for all commands.", 1
разнеси

2021-05-20 06:48 UTC, corwinnn requested changes

2021-05-20 06:48 UTC, corwinnn commented on main.py
> +bot = tb.TeleBot("Your TOKEN")
бери из переменных окружения

2021-05-22 13:50 UTC, corwinnn approved these changes

2021-07-29 11:42 UTC, merged